/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(win_min_max.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(93183bf00c9c2c5ea903320bdb3a9192)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/kb3gtn/win_min_max.h>
// pydoc.h is automatically generated in the build directory
#include <win_min_max_pydoc.h>

void bind_win_min_max(py::module& m)
{

    using win_min_max    = gr::kb3gtn::win_min_max;


    py::class_<win_min_max, gr::sync_decimator,
        std::shared_ptr<win_min_max>>(m, "win_min_max", D(win_min_max))

        .def(py::init(&win_min_max::make),
           D(win_min_max,make)
        )
        



        ;




}








