/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-kb3gtn
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_KB3GTN_API_H
#define INCLUDED_KB3GTN_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_kb3gtn_EXPORTS
#define KB3GTN_API __GR_ATTR_EXPORT
#else
#define KB3GTN_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_KB3GTN_API_H */
